name = "GEOCLIM"
uuid = "3dbb98da-0543-4a00-be75-dcc1e89fb417"
authors = ["Mark Baum <markmbaum@protonmail.com>"]
version = "0.1.0"

[deps]
BasicInterpolators = "26cce99e-4866-4b6d-ab74-862489e035e0"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"

[compat]
julia = "1"
BasicInterpolators = "0.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
